/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package layer;

import layer.annotations.Module;
import layer.entity.LayerContainer;
import layer.extend.Layer;
import layer.extend.LayerController;
import layer.extend.LayerProvider;
import layer.instance.InstanceFactory;
import layer.layer.Logger;
import layer.module.LayerModule;
import layer.module.ModuleFactory;
import org.junit.Test;
import layer.annotations.*;


public class LibraryTest {
	@LayerClass
	class console extends Layer {
		public void log(String... name) {
			System.out.println(String.join(" ", name));
		}
	}
	
	@LayerClass
	class fs extends Layer {
		@Require
		Logger logger;
		@Config()
		String version = "0.0.1";
		
		public void printName() {
			logger.warn("fs版本 v" + version + " 已经过时,强制运行会导致爆炸");
		}
	}
	
	@LayerClass
	class fs_mysql extends fs {
		@Override
		public void setup() {
			version = "0.0.2";
		}
	}
	
	@LayerClass
	class a extends Layer {
		@Require
		Logger logger;
		@Require
		b b;
		
		public void name() {
			logger.info("A is a");
		}
		
		@Override
		public void run() {
			b.name();
		}
	}
	
	@LayerClass
	class b extends Layer {
		@Require
		Logger logger;
		@Require
		a a;
		
		public void name() {
			logger.info("B is b");
		}
		
		@Override
		public void run() {
			a.name();
		}
	}
	
	@LayerClass
	class run extends Layer {
		@Require()
		fs fs;
		@Require
		Logger logger;
		@Override
		public void run() {
			logger.suc();
			logger.suc("mount <-> success");
			fs.printName();
			fs.logger.info("run finish %s", "code 0");
		}
	}
	
	@Provider
	class p0 extends LayerProvider {
		public String name = "p0";
		@Require()
		@Import(name = "ch")
		p1 p1;
		public void loop() {
			p1.logger.warn("使用了循环依赖的模块和循环依赖的对象");
		}
	}
	
	@Provider
	class p1 extends LayerProvider {
		public String name = "p1";
		@Require
		Logger logger;
		@Require(name = "p0")
		@Import(name = "main")
		p0 loopObj;
		
		@Override
		public void run() {
			loopObj.loop();
		}
	}
	
	@Controller
	class c0 extends LayerController {
		@Require()
		p0 p0;
		public void test() {
			p0.p1.logger.info("..child.child.logger init ..");
		}
		
		@Override
		public void run() {
			test();
		}
	}
	
	@Module(name = "ch")
	class module_ch extends LayerModule {
		@Override
		public void handelInstance(InstanceFactory f) {
			f.instance("logger", new Logger());
		}
		
		public module_ch() {
			provider(new p1());
			//循环模块
			imports("main");
		}
	}
	
	@Module(name = "main")
	class module_main extends LayerModule {
		public module_main() {
			controller(new c0());
			provider(new p0());
			imports(new module_ch());
		}
	}
	
	
	@Test
	public void someLibraryMethodReturnsTrue() {
		new InstanceFactory()
			.deployInfo()
			.include(
				new console(),
				new fs(),
				new fs_mysql(),
				new run(),
				new a(),
				new b()
			)
			.instance("a", t -> {
			
			})
			.instance("b", t -> {
			
			})
			.instance("logger", t -> t
				.implement(new Logger())
				.config("name", "I")
			)
			.instance("fs-logger", t -> t
				.implement(new Logger())
				.config("name", "fs")
			)
			.instance("run-logger", t -> t
				.implement(new Logger())
				.config("name", "run")
			)
			.instance("console")
			.instance("fs_mysql", t -> t.require("logger", "fs-logger"))
			.instance("fs", t -> t
				.config("name", "hhh")
				.require("console")
				.require("logger", "fs-logger")
			)
			.instance("run", t -> t
				.require("fs", "fs_mysql")
				.require("logger", "run-logger")
			)
			.deploy();
		new ModuleFactory()
			.deployInfo()
			.include(new module_main())
			.deploy();
	}
}
