/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package layer;

import layer.entity.Instance;
import layer.entity.Layer;
import org.junit.Test;
import layer.Interface.*;


public class LibraryTest {
	@layer
	static class console extends Layer {
		public void log(String... name) {
			System.out.println(String.join(" ", name));
		}
	}
	
	@layer
	static class fs extends Layer {
		@require()
		console console;
		@config()
		String name;
		
		public void printName() {
			console.log("name:" + name);
		}
	}
	
	@layer
	static class run extends Layer {
		@require()
		fs fs;
		
		@Override
		public void run() {
			fs.console.log("run success");
			fs.printName();
		}
	}
	
	@Test
	public void someLibraryMethodReturnsTrue() {
		new Instance()
			.provide(new Layer[]{
				new console(),
				new fs(),
				new run(),
			})
			.instance("console")
			.instance("fs", t -> t
				.config("name", "hhh")
				.require("console"))
			.instance("run", t -> t
				.require("fs"))
			.deploy();
	}
}
